require 'rubygems'
require 'hotcocoa/application'

app = HotCocoa::Application.new '__APPLICATION_NAME__.appspec'

desc 'Build the application'
task :build do
  app.build
end

desc 'Build a deployable version of the application'
task :deploy do
  app.deploy
end

desc 'Build and execute the application'
task :run => [:build] do
  app.run
end

desc 'Cleanup build files'
task :clean do
  app.clean
end

task :default => [:run]
